import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml",
    "~/.config/alacrity/keybindings.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 18.0

[font.normal]
family = "MesloLGM Nerd Font Mono"
style = "Regular"

[font.bold_italic]
family = "MesloLGM Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MesloLGM Nerd Font Mono"
style = "Italic"

