# Do not insert a blank line between shell prompts
# add_newline = false

format = """
$all\
$conda\
$cmd_duration\
$line_break\
$directory\
$line_break\
$battery\
$jobs\
$character"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
orange = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"


[git_branch]
style = "bold fg:lavender"
symbol = ""
format = '[$symbol $branch ]($style)'

[git_status]
style = "bold fg:lavender"
format = '[($all_status$ahead_behind) ]($style)'

[git_state]
style = "fg:lavender"

[conda]
symbol = " "
style = "bold fg:flamingo"
format = '[$symbol$environment ]($style)'
disabled = false
ignore_base = false

[[battery.display]]
threshold = 10
style = 'bold red'

[directory]
style = "fg:text"
format = "[$path ]($style)"
truncation_length = 7
truncate_to_repo = false
truncation_symbol = "…/"

[cmd_duration]
disabled = false
style = "fg:Peach"
format = '[󰄉 $duration ]($style)'

[line_break]
disabled = false

[jobs]
format = "[$number$symbol ]($style)"
style = "fg:green"
symbol = "󰜎"

[character]
disabled = false
success_symbol = '[❯](fg:green)'
error_symbol = '[❯](fg:red)'

# Disable the package module, hiding it from the prompt completely
[rlang]
disabled = true
[python]
disabled = true
[lua]
disabled = true
