[general]
import = [
  "~/.config/alacritty/themes/themes/catppuccin_mocha.toml",
  "/Users/sreenivasan/.config/alacritty/keybindings.toml",
]

working_directory = "/Users/sreenivasan/"

[env]
TERM = "xterm-256color"

[font]
size = 19.0
normal = { family = "MesloLGM Nerd Font Mono", style = "Regular" }
bold = { family = "MesloLGM Nerd Font Mono", style = "Bold" }
bold_italic = { family = "MesloLGM Nerd Font Mono", style = "Bold Italic" }
italic = { family = "MesloLGM Nerd Font Mono", style = "Italic" }

[cursor]
style.blinking = "Always"
blink_interval = 400
blink_timeout = 4

[window]
padding = { x = 10, y = 5 }
dynamic_padding = true
decorations = "full"
# opacity = 0.70
blur = true
# startup_mode =  "Fullscreen"
option_as_alt = "OnlyRight"

[[keyboard.bindings]]
key = "NumpadEnter"
chars = "\r"
